version: '3.3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    build:
      context: .
    container_name: php_container
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - app-network
    command: >
      sh -c "
      composer install &&
      php artisan migrate --force &&
      php-fpm
      "

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psico-case
      # MYSQL_USER: user
      # MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
